### ISSUE TITLE
Error with undefined function for cleaning

### ISSUE THREAD

**Issue by 5ika** [zecka/pictifly#1]
Pictifly throws a fatal error when it tries to remove some useless images.

```
PHP Fatal error: Uncaught Error: Call to undefined function pf_remove_attachment_dir() in /var/www/html/wp-content/plugins/pictifly/kernel/media-library/pf_keypoint_field.php:71
```

Apparently, it cannot find `pf_remove_attachment_dir` in https://github.com/zecka/pictifly/blob/master/kernel/classes/class-pf-helper.php

**Comment by zecka** [comment]
Hello, this issue is fixed on the new version (0.4.1). Thank's for feedback.
